#!/usr/bin/env bash
# Fetch all Outline secrets from GCP Secret Manager and write /opt/outline/.env (mode 600).
# Re-run after rotating any secret in Secret Manager.
# Run on the VM as root (or a user that can chmod 600 the file).
set -euo pipefail

PROJECT=robust-fin-495718-a9
ENV_FILE=/opt/outline/.env

read_required() {
  gcloud secrets versions access latest --secret="$1" --project="$PROJECT" 2>/dev/null \
    || { echo "ERROR: secret $1 has no value yet" >&2; exit 1; }
}

read_optional() {
  gcloud secrets versions access latest --secret="$1" --project="$PROJECT" 2>/dev/null || true
}

umask 077
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

{
  echo "# Auto-generated by load-secrets.sh — do not edit. Re-run to refresh."
  echo "SECRET_KEY=$(read_required outline-secret-key)"
  echo "UTILS_SECRET=$(read_required outline-utils-secret)"
  echo "POSTGRES_PASSWORD=$(read_required outline-postgres-password)"
  echo "REDIS_PASSWORD=$(read_required outline-redis-password)"
  echo "GOOGLE_CLIENT_ID=$(read_required outline-oauth-client-id)"
  echo "GOOGLE_CLIENT_SECRET=$(read_required outline-oauth-client-secret)"
  echo "SMTP_PASSWORD=$(read_optional outline-smtp-password)"
} > "$TMP"

mv "$TMP" "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE"

# Drive SA JSON key — used by rclone in backup.sh to push to Workspace Shared Drive.
DRIVE_KEY_FILE=/opt/outline/drive-sa-key.json
if gcloud secrets versions access latest --secret=outline-drive-sa-key --project="$PROJECT" 2>/dev/null > "${DRIVE_KEY_FILE}.tmp"; then
  mv "${DRIVE_KEY_FILE}.tmp" "$DRIVE_KEY_FILE"
  chmod 600 "$DRIVE_KEY_FILE"
  echo "Wrote $DRIVE_KEY_FILE"
else
  rm -f "${DRIVE_KEY_FILE}.tmp"
  echo "Skipped $DRIVE_KEY_FILE (secret not yet populated)"
fi
