apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: overseerr
  annotations:
    external-dns.alpha.kubernetes.io/target: ingress-ext.haynesnetwork.com
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/href: "https://overseerr.haynesnetwork.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/name: Overseerr
    gethomepage.dev/description: Media request management
    gethomepage.dev/icon: overseerr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`overseerr.haynesnetwork.com`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: haynestower
          port: 5055
      middlewares:
        - name: default-headers
  tls:
    secretName: certificate-haynesnetwork