---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mcp-grafana-secret
    template:
      engineVersion: v2
      data:
        GRAFANA_SERVICE_ACCOUNT_TOKEN: "{{ .GRAFANA_SERVICE_ACCOUNT_TOKEN }}"
  dataFrom:
    - extract:
        key: grafana
