---
groups:
  - name: plexops
    rules:
      - alert: PlexopsDatabaseIsBusy
        expr: |
          sum by (app) (count_over_time({app="plexops"} |~ "(?i)retry busy DB"[5m])) > 0
        for: 5m
        annotations:
          summary: >-
            {{ $labels.app }} is experiencing database issues
        labels:
          severity: critical
