---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bazarr-secret
  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: media-stack
        property: RADARR_API_KEY
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: media-stack
        property: SONARR_API_KEY
