---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./crds/ks.yaml
  - ./network/ks.yaml
  - ./scheduling/ks.yaml
  - ./templates/ks.yaml
  - ./storage/ks.yaml
  - ./session-config/ks.yaml
