---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: kometa-config-files
    files:
      - movies-charts.yml=./config/movies-charts.yml
      - movies-collections.yml=./config/movies-collections.yml
      - shows-collections.yml=./config/shows-collections.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
