apiVersion: v1
kind: PersistentVolume
metadata:
  name: gasha01-nfs-synthetic-9c9e68c4
  labels:
    app.kubernetes.io/name: gasha01-nfs-synthetic-9c9e68c4
    dev-env.haynesops.com/nfs-synthetic: nfs-synth-89179a1b4841452cb1ec30f29c9e68c4
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 16Mi
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  claimRef:
    namespace: dev-agents
    name: gasha01-nfs-synthetic-9c9e68c4
  mountOptions:
  - nfsvers=4.2
  - hard
  nfs:
    server: gasha01.haynesnetwork
    path: /hdd-nfs-repl
    readOnly: false
