apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gasha01-nfs-synthetic-9c9e68c4
  namespace: dev-agents
  labels:
    app.kubernetes.io/name: gasha01-nfs-synthetic-9c9e68c4
    dev-env.haynesops.com/nfs-synthetic: nfs-synth-89179a1b4841452cb1ec30f29c9e68c4
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ''
  volumeName: gasha01-nfs-synthetic-9c9e68c4
  resources:
    requests:
      storage: 16Mi
