---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../../shared/components/common/repos/app-template
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./lazylibrarian/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./slskd/ks.yaml
  - ./soularr/ks.yaml
  - ./ytdl-sub/ks.yaml
