---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-env-system
configMapGenerator:
  - name: dev-env-project-catalog
    files:
      - catalog.json
generatorOptions:
  disableNameSuffixHash: true
resources:
  - operator.yaml
