# shellcheck shell=bash
# coordination-lib.sh — the SINGLE SOURCE of the gate/triage coordination logic.
#
# Sourced (never executed) by BOTH:
#   health-gate/app/resources/gate.sh    (CronJob upgrade-health-gate)
#   shepherd/app/resources/triage.sh     (CronJob upgrade-shepherd-triage)
# so the two independent CronJobs compute the SAME regression signature (the
# coordination key). This file replaces the old "byte-identical duplicated block"
# convention (2026-07-06) — it ships as its own ConfigMap (`upgrade-coordination-lib`,
# generated by the health-gate kustomization, mounted at /opt/coordination in both
# pods; the shepherd ks already dependsOn the health-gate ks, so ordering holds).
#
# The coordination set is Flux (Kustomization/HelmRelease) NotReady + persisted-unhealthy
# pods ONLY — the deploy-health signals an UPGRADE regresses through. Firing critical alerts
# are DELIBERATELY NOT here: Alertmanager already pages every critical with full context, and
# the gate must not be a second, context-poor alert relay (a self-healed soularr OOMKill once
# double-paged as a vague "upgrade-gate: OOMKilled" — the reason this was removed 2026-07).
# The same principle covers a Job whose FAILURE is the transport of a critical alert (an
# exit-1 countdown monitor): its pod template opts in with the annotation read by
# pod_failure_is_the_alert below, and collect_regressions drops its Failed pods (2026-09-19).
#
# CONTRACT: the caller must set $NOW (epoch) and $PROM (Prometheus base URL) before
# calling collect_regressions. Everything here is READ-ONLY.
STATE_NS="${UPGRADE_AGENT_NAMESPACE:-upgrade-agent}"
STATE_CM="${UPGRADE_REMEDIATION_STATE_CM:-upgrade-remediation-state}"
SIG_OFFSET="${COORD_SIG_OFFSET:-10m}"
# Canonical persisted-unhealthy-pods selectors. `offset` MUST directly follow a SELECTOR:
# `(expr) offset 10m` is a Prometheus PARSE error -> 400 -> empty body -> a false-green.
SIG_POD_WAITING='kube_pod_container_status_waiting_reason{reason=~"CrashLoopBackOff|ImagePullBackOff|ErrImagePull|CreateContainerError|CreateContainerConfigError"}'
SIG_POD_PHASE='kube_pod_status_phase{phase=~"Pending|Failed|Unknown"}'
SIG_POD_QUERY="( (${SIG_POD_WAITING} == 1) or (${SIG_POD_PHASE} == 1) ) and ( (${SIG_POD_WAITING} offset ${SIG_OFFSET} == 1) or (${SIG_POD_PHASE} offset ${SIG_OFFSET} == 1) )"

# ── STALE-CORPSE FILTER (2026-07-28) ── a terminal Failed pod is dropped from the
# coordination set when it is demonstrably HISTORY, not a live regression:
#   A0. own Job converged — the pod's OWN Job reports succeeded>=1 (2026-09-13)
#   A.  superseded — its owning CronJob has a NEWER Job that succeeded
#   B.  ancient    — Failed and older than COORD_STALE_POD_HOURS (default 24h)
# Why: failedJobsHistory retention keeps Error/Init:Error pods in the API for days;
# the phase query counted them forever, so one ghost list (11 pods, 4–17 days old)
# re-paged critical every 6h and re-summoned remediate (07-24/25/28 — each run
# concluded "stale pre-existing pods, no regression"). Live signals are untouched:
# CrashLoop/ImagePull waiting pods are actively restarting (not phase=Failed),
# Pending/Unknown have no ceiling, and a CronJob whose LATEST run failed still
# counts (rule A requires a newer SUCCESS, and A0 requires the pod's own Job to have
# actually converged — a Job that exhausts backoffLimit never sets succeeded, so a
# genuinely failing job still pages). Any lookup error KEEPS the pod —
# fail-noisy, never fail-blind. A pod already deleted from the API is dropped (it
# can still satisfy the query via the offset side while KSM series linger).
COORD_STALE_POD_HOURS="${COORD_STALE_POD_HOURS:-24}"
pod_is_stale_corpse() {  # $1=ns $2=pod ; rc0 = drop from the coordination set
  local ns="$1" pod="$2" out rc pj phase start job cj jobs newer_ok
  out="$(kubectl -n "$ns" get pod "$pod" -o json 2>&1)"; rc=$?
  if [ "$rc" -ne 0 ]; then
    case "$out" in
      *NotFound*|*"not found"*) return 0 ;;   # gone from the API -> not a live signal
      *) return 1 ;;                          # unreadable -> keep (fail-noisy)
    esac
  fi
  pj="$out"
  phase="$(printf '%s' "$pj" | jq -r '.status.phase // ""' 2>/dev/null)"
  [ "$phase" = "Failed" ] || return 1         # only terminal corpses are filterable
  # A. superseded — owning CronJob has a newer succeeded Job
  job="$(printf '%s' "$pj" | jq -r '[.metadata.ownerReferences[]? | select(.kind=="Job") | .name][0] // ""' 2>/dev/null)"
  if [ -n "$job" ]; then
    jobs="$(kubectl -n "$ns" get jobs -o json 2>/dev/null)"
    if [ -n "$jobs" ]; then
      # A0. the pod's OWN Job already converged (2026-09-13). A Job with
      # backoffLimit>=1 that fails its first attempt and succeeds on the retry leaves
      # the failed ATTEMPT behind as a Failed pod, forever, while the Job itself reads
      # Complete 1/1. That corpse is an artifact of a SUCCESSFUL job, not a regression.
      #
      # Rule A below cannot catch this: it looks for a strictly NEWER Job from the same
      # CronJob (creationTimestamp > $t0), and a same-Job retry is not a newer Job. Rule
      # B cannot either — it waits out COORD_STALE_POD_HOURS (24h). So before this, every
      # retried-then-succeeded cron Job paged critical for a full day and auto-remediation
      # could never converge, because there was nothing wrong to fix.
      #
      # Observed: frontend/cigar-journal-crawl-enrich-fleet-29821080 — attempt 1
      # (-6b7cw) exit 1, attempt 2 (-fk9dc) Completed, Job Complete 1/1, and the gate
      # still paged "unhealthy >10m after an UPGRADE and auto-remediation FAILED".
      own_ok="$(printf '%s' "$jobs" | jq -r --arg j "$job" \
        '[.items[] | select(.metadata.name==$j) | (.status.succeeded // 0)][0] // 0' 2>/dev/null)"
      if [ "${own_ok:-0}" -ge 1 ] 2>/dev/null; then
        return 0
      fi
      cj="$(printf '%s' "$jobs" | jq -r --arg j "$job" '[.items[] | select(.metadata.name==$j) | .metadata.ownerReferences[]? | select(.kind=="CronJob") | .name][0] // ""' 2>/dev/null)"
      if [ -n "$cj" ]; then
        # RFC3339 creationTimestamps compare correctly as strings (same format, Z).
        newer_ok="$(printf '%s' "$jobs" | jq -r --arg j "$job" --arg cj "$cj" '
          ([.items[] | select(.metadata.name==$j) | .metadata.creationTimestamp][0] // "") as $t0
          | [ .items[]
              | select(any(.metadata.ownerReferences[]?; .kind=="CronJob" and .name==$cj))
              | select($t0 != "" and .metadata.creationTimestamp > $t0)
              | select((.status.succeeded // 0) >= 1) ] | length' 2>/dev/null)"
        [ "${newer_ok:-0}" -gt 0 ] 2>/dev/null && return 0
      fi
    fi
  fi
  # B. ancient — Failed longer than the ceiling (a live cron failure re-fails on
  # FRESH pods each schedule, so an old corpse only means retention, not regression)
  start="$(printf '%s' "$pj" | jq -r '(.status.startTime // .metadata.creationTimestamp // "") | sub("\\.[0-9]+";"") | fromdateiso8601? // 0' 2>/dev/null)"
  if [ "${start:-0}" -gt 0 ] 2>/dev/null && [ "$(( NOW - start ))" -gt "$(( COORD_STALE_POD_HOURS * 3600 ))" ]; then
    return 0
  fi
  return 1
}

# ── FAILURE-IS-THE-ALERT FILTER (2026-09-19) ── a terminal Failed pod is dropped from the
# coordination set when its pod template declares that failing IS how it signals:
#   upgrade-agent.haynesnetwork.com/failure-is-the-alert: <the critical alert that pages it>
# Some CronJobs are monitors whose only output is their exit code — an exit-1 countdown
# (frontend/cigar-journal-credential-expiry: "the Job's own terminal failure IS the
# alert"; exit 1 at T-7d on a credential -> kube_job_failed ->
# CigarJournalCredentialExpiring -> Pushover). Nothing is deployed wrong when such a pod
# fails, so it is not a deploy-health signal: the gate would be the second, context-poor
# relay the header rules out, and the triage lane's path attribution turns it into an
# "upgrade regression" whenever ANY merge touches the app's path inside the 3h lookback
# — a coincidence, not a mechanism.
#
# Observed 2026-09-19 (esc-shepherd-99e57e39): the credential monitor exited 1 at 12:00Z
# (dev-env-cli, 7 days left — a true positive, already paged by its own alert at 08:07
# ET). A same-day fix to the ALERT TEXT (#2970, prometheusrule.yaml only, dev session)
# merged at 14:22Z, inside the lookback; the 14:30Z triage attributed the pod to it,
# summoned remediate, which correctly broke glass ("needs a human token re-mint"), and
# the no-PR outcome escalated — a second page for a condition the alert had already
# reported. Rules A0/A/B cannot cover this: the Job genuinely failed, it is the newest
# Job of its CronJob, and it is hours old.
#
# Scope is deliberately narrow: the pod must be phase=Failed (a terminal exit). A
# Pending/ImagePull/CrashLoop pod from the same CronJob is a real deploy fault and stays
# in the set. Any lookup error KEEPS the pod (fail-noisy, like the corpse filter). The
# annotation's value is the covering alert and is logged on every drop, so a wrong
# opt-in is auditable; the contract for setting it is that EVERY terminal failure of
# the pod already pages critical with context. It is NOT for a Job whose failure is a
# genuine fault that merely alerts through kube_job_failed (outline-backup: a missing
# backup IS broken state, and the shepherd may still have a bump to revert there).
COORD_FAILURE_IS_THE_ALERT_KEY="${COORD_FAILURE_IS_THE_ALERT_KEY:-upgrade-agent.haynesnetwork.com/failure-is-the-alert}"
pod_failure_is_the_alert() {  # $1=ns $2=pod ; rc0 = drop from the set (stdout: the covering alert)
  local ns="$1" pod="$2" alert
  alert="$(kubectl -n "$ns" get pod "$pod" -o json 2>/dev/null \
    | jq -r --arg k "$COORD_FAILURE_IS_THE_ALERT_KEY" \
        'select(.status.phase == "Failed") | .metadata.annotations[$k] // empty' 2>/dev/null)"
  [ -n "$alert" ] || return 1   # not Failed, not annotated, or unreadable -> keep
  printf '%s' "$alert"
}

# collect_regressions — populate the globals REG_IDS (sorted-unique regression identifiers,
# one per line) and SIG_PODS_STATUS (ok|blind). Identifier forms (stable + sortable):
#   flux/<Kind>/<ns>/<name>   pod/<ns>/<pod>
# Requires $NOW (epoch) and $PROM set by the caller. Read-only; never writes anything.
#
# FIRST-FAILURE ANCHORING (2026-07-17): the >600s persistence age is measured from the
# OLDEST failure-indicating condition transition, NOT just Ready's. Ready's
# lastTransitionTime churns during a Helm rollback loop (each retry flips Ready
# Unknown->False, resetting the clock) — the mcp-grafana 0.17.2 incident looped
# upgrade->rollback for 25 min and every gate cycle saw Ready as "~9 min old", so it
# was never selected. Stable anchors that k8s condition semantics do NOT bump on
# retries (status stays constant): Released=False (HR UpgradeFailed), Stalled=True
# (HR RetriesExceeded), Healthy=False (Kustomization health check). A leftover
# failure condition can only anchor while Ready!=True (the entry gate), and Flux
# clears all three on recovery, so a healthy resource mid-reconcile (Ready=Unknown,
# fresh) is still excluded. Per-timestamp parse errors drop that TIMESTAMP (never
# abort the whole pipeline into a false-green — `fromdateiso8601?`); an item whose
# every anchor is unparseable is skipped.
collect_regressions() {
  SIG_PODS_STATUS=ok
  local flux_ids pods_json pods_ids
  flux_ids="$(kubectl get kustomizations.kustomize.toolkit.fluxcd.io,helmreleases.helm.toolkit.fluxcd.io -A -o json 2>/dev/null \
    | jq -r --argjson now "$NOW" '.items[] | . as $i
        | (.status.conditions // []) as $cs
        | ($cs[]? | select(.type=="Ready" and .status!="True")) as $c
        | ([ $c.lastTransitionTime,
            ($cs[]? | select(.status=="False" and (.type=="Released" or .type=="Healthy")) | .lastTransitionTime),
            ($cs[]? | select(.status=="True" and .type=="Stalled") | .lastTransitionTime)
          ]
          | map(select(type=="string") | (sub("\\.[0-9]+";"") | fromdateiso8601? // empty))
          | min) as $t
        | select($t != null and ($now - $t) > 600)
        | "flux/\(.kind)/\($i.metadata.namespace)/\($i.metadata.name)"' 2>/dev/null)"
  pods_json="$(curl -sf --max-time 15 "$PROM/api/v1/query" --data-urlencode "query=$SIG_POD_QUERY" 2>/dev/null)"
  if [ -z "$pods_json" ]; then
    SIG_PODS_STATUS=blind
    pods_ids=""
  else
    pods_ids="$(printf '%s' "$pods_json" | jq -r '.data.result[] | "pod/\(.metric.namespace)/\(.metric.pod)"' 2>/dev/null)"
  fi
  # Drop pods whose failure is their alert (pod_failure_is_the_alert), then stale corpses
  # (pod_is_stale_corpse). Per-candidate kubectl is fine: the set is normally 0–12
  # entries on a 30-min cadence.
  if [ -n "$pods_ids" ]; then
    local _kept="" _id _ns _pod _alert
    while IFS= read -r _id; do
      [ -z "$_id" ] && continue
      _ns="${_id#pod/}"; _pod="${_ns#*/}"; _ns="${_ns%%/*}"
      if _alert="$(pod_failure_is_the_alert "$_ns" "$_pod")"; then
        type log >/dev/null 2>&1 && log "coordination: dropped failure-is-the-alert pod ${_ns}/${_pod} (terminal exit is the transport of critical alert '${_alert}'; Alertmanager pages it — not a deploy-health signal)"
      elif pod_is_stale_corpse "$_ns" "$_pod"; then
        type log >/dev/null 2>&1 && log "coordination: dropped stale corpse pod ${_ns}/${_pod} (superseded/ancient/gone)"
      else
        _kept="${_kept}${_id}"$'\n'
      fi
    done <<EOF
$pods_ids
EOF
    pods_ids="$_kept"
  fi
  REG_IDS="$(printf '%s\n%s\n' "$flux_ids" "$pods_ids" | sed '/^$/d' | LC_ALL=C sort -u)"
}

# sig_of — stable short (12-hex) signature of the newline-joined identifier list ($1).
# sha256 via whichever tool exists; we slice the 64-hex out so the tool's output framing
# does not matter (identical value in the debian gate image and the node shepherd image).
sig_of() {
  printf '%s' "$1" \
    | { sha256sum 2>/dev/null || shasum -a 256 2>/dev/null || openssl dgst -sha256 2>/dev/null; } \
    | grep -oE '[0-9a-f]{64}' | head -1 | cut -c1-12
}

# state_get — compact-JSON entry for signature $1, or "" (FAIL-SAFE for the gate: any error
# => ""). Triage uses state_read() instead (it must distinguish unreadable from absent).
state_get() {
  kubectl -n "$STATE_NS" get configmap "$STATE_CM" -o json 2>/dev/null \
    | jq -c --arg k "$1" '(.data[$k] // "") | if . == "" then empty else (fromjson? // {}) end' 2>/dev/null
}
# jget — read field $2 from a compact-JSON entry $1; empty string if absent.
jget() { printf '%s' "$1" | jq -r --arg f "$2" '.[$f] // ""' 2>/dev/null; }
