---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appdaemon
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: appdaemon-secret
    template:
      engineVersion: v2
      data:
        TOKEN: "{{ .TOKEN }}"
        OPENAPI_TOKEN: "{{ .OPENAPI_TOKEN }}"
        MEDIA_FS_ROOT: "{{ .MEDIA_FS_ROOT }}"
        IMMICH_API_KEY: "{{ .IMMICH_API_KEY }}"
        GEMINI_API_KEY: "{{ .GEMINI_API_KEY }}"
        secrets.yaml: |
          ha_url: "http://home-assistant.home-automation.svc.cluster.local:8123"
          token: "{{ .TOKEN }}"
          media_fs_root: "{{ .MEDIA_FS_ROOT }}"
          immich_url: "http://immich-server.photos.svc.cluster.local:2283"
          comfyui_url: "http://comfyui.ai.svc.cluster.local:8188"
        appdaemon.yaml: |
          appdaemon:
            time_zone: America/New_York
            latitude: 0
            longitude: 0
            elevation: 0

            plugins:
              HASS:
                type: hass
                ha_url: !secret ha_url
                token: !secret token
                ws_max_msg_size: 8388608
                ws_timeout: 60

          http:
            url: http://0.0.0.0:5050

          api:
          admin:
  dataFrom:
    - extract:
        key: appdaemon
