---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
configMapGenerator:
  - name: dns-canary-script
    files:
      - canary.sh=./resources/canary.sh
      - main.go=./resources/main.go
