# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../../shared/components/common/repos/app-template
resources:
  - ./pvc.yaml
  - ./rbac.yaml
  - ./networkpolicy.yaml
  - ./ingressroute.yaml
  - ./helmrelease.yaml
